Aggiunta verbali
MercurySeven/project-docs pull request #68
Opened 2021-05-12 15:14 UTC by Edivad99

- VE_2021/05/06

2021-05-24 10:26 UTC, lucreziagradi commented
Sull'ultimo verbale esterno una delle decisioni finali non è una decisione

2021-05-26 20:58 UTC, lucreziagradi approved these changes

2021-05-26 22:33 UTC, RakuJa requested changes
L'ultimo verbale esterno è troppo vuoto, aggiungere almeno una decisione

2021-05-27 13:07 UTC, RakuJa approved these changes

2021-05-27 13:07 UTC, merged