Verbali 30/11 07/12
MercurySeven/project-docs pull request #7
Opened 2020-12-20 09:25 UTC by Edivad99

- Aggiunto verbali
- Sistemato prima pagina degli altri verbali

2020-12-20 20:37 UTC, Edivad99 commented on Interni/Verbali Interni/2020_11_23/components/registro_modifiche.tex
> +		v1.0.0 & \DataDoc{} & Davide Albiero &  \textit{Responsabile di Progetto} & Approvazione del documento \\
Cambiare il nome

2020-12-20 20:37 UTC, Edivad99 commented
Convertire i nomi da progettista a analista

2020-12-20 22:55 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_07/components/verbale.tex
> +È stato spiegato ad ogni membro del gruppo come verrà gestito il repository riguardante la documentazione. Sono state mostrate le pratiche che ogni componente del gruppo dovrà seguire per caricare i
Magari spiegare sinteticamente che il merge avviene tramite pull request

2020-12-20 23:02 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_07/components/verbale.tex
> +A Tommaso e Matteo è stato assegnato la scrittura del \PdP .
Può andare bene, se riesci ad ampliare un minimo sarebbe meglio (es. come ad esempio ha fatto Lucrezia nel verbale del 30 "Dopo aver svolto individualmente lo studio sulle norme di progetto, Francesco e Daniele si sono proposti di cominciare la stesura delle suddette.") Se non riesci ad ampliare va bene così.

2020-12-20 23:11 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_07/components/verbale.tex
> +		VI\_\DataMeeting{}.1 & Tutti i componenti ora sanno come funziona GitHub. \\
Sembra molto poco formale il riepilogo delle decisioni, qualcosa tipo "Fornite nozioni base sullo strumento _GitHub_."

2020-12-20 23:11 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_07/components/verbale.tex
> +		VI\_\DataMeeting{}.3 & Daniele verificherà il documento. \\
Indicare che documento

2020-12-20 23:12 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_07/components/verbale.tex
> +		VI\_\DataMeeting{}.2 & Inviata la mail all'azienda. \\
Indicare cosa riguarda la mail, mail di domande? Bisogna specificare sinteticamente

2020-12-20 23:13 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_07/components/verbale.tex
> +		VI\_\DataMeeting{}.4 & Assegnato il documento Piano di Progetto. \\
Assegnata la stesura del documento, non il documento e basta. inoltre usa \PdP per scrivere Piano di Progetto (così è in italics automaticamente)

2020-12-20 23:15 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/informazioni.tex
> +\newcommand{\DataDoc}{2020-12-19}
La data del documento principale (VI_2020_12_14) non corrisponde con la data della stesura del documento, cambia il nome del file in VI_2020_12_19

2020-12-20 23:15 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/VI_2020_12_14.tex
> +\documentclass[a4paper, oneside]{article}
Guarda su informazioni.tex cosa ho scritto, TLDR cambia il nome di questo file in VI_2020_12_19

2020-12-20 23:16 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/components/verbale.tex
> +Sono stati discussi i punti rilevanti emersi durante la chiamata Zoom del 2020-12-17 con il prof. Tullio Vardanega:
Nome personale in italics " _prof. Tullio Vardanega_"

2020-12-20 23:17 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/components/verbale.tex
> +	\item \textbf{scadenze}: le scadenze diventano date minime di consegna oltre le quali ogni gruppo, previa richiesta, è libero di scegliere le proprie
Il gruppo fa richiesta di una data specifica, non è piena libertà.

2020-12-20 23:19 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/components/verbale.tex
> +	\item \textbf{documenti}: è stato fissato un numero massimo di pagine per ogni documento e mantenedo i documenti allineati con l'effettivo stato di avanzamento del progetto.
La frase risulta leggermente sconnessa, cambiare in qualcosa del tipo [..] per ogni documento ed inoltre si sono stabilite regole per ridurre la zavorra possibile nei documenti, in modo da renderli facilmente migliorabili e più allineati con l'effettivo stato di avanzamento del progetto. " (Ovviamente è un suggerimento scritto di getto, pensaci sopra)

2020-12-20 23:20 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/components/verbale.tex
> +Questo per poter favorire un buon numero di riassegnazioni e al tempo stesso permettere al singolo individuò di acquisire famigliarità con il ruolo assegnatogli.
*familiarità

2020-12-20 23:22 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/components/verbale.tex
> +È stato esposto ai membri del gruppo il funzionamento dello script creato da Davide e Francesco per la generazione e la gestione automatica del glossario.
Dare una breve spiegazione del funzionamento

2020-12-20 23:25 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/components/verbale.tex
> +		VI\_\DataMeeting{}.4 & Ogni membro sanno utilizzare il nuovo script per il glossario. \\
Risulta poco formale il riepilogo delle decisioni
Es 1 Specificare cosa tratta la mail inviata
Es 3 Decisa una durata fissa di ogni rotazione dei ruoli
Es 4 Fornite nozioni per permettere al gruppo il pieno utilizzo dello script per il glossario.

Per quanto riguarda il secondo punto sembra abbastanza buono, magari aggiungerei che è stato definito un numero massimo di pagine per documento

2020-12-20 23:27 UTC, RakuJa requested changes
I due verbali più recenti **devono** essere revisionati seguendo le indicazioni

2020-12-28 21:20 UTC, Matteo- commented on Interni/Verbali Interni/2020_12_18/components/verbale.tex
> +		VI\_\DataMeeting{}.4 & Ogni membro sanno utilizzare il nuovo script per il glossario. \\
sistemato, per quanto riguarda il numero di pagine nel punto 2 non essendo una decisione presa da noi lo metto comunque?

2020-12-29 13:35 UTC, RakuJa approved these changes

2020-12-29 13:36 UTC, RakuJa commented on Interni/Verbali Interni/2020_12_18/components/verbale.tex
> +		VI\_\DataMeeting{}.4 & Ogni membro sanno utilizzare il nuovo script per il glossario. \\
Va bene come hai scritto ora!

2020-12-29 13:37 UTC, merged